packages:
  - apps/*
  - packages/*
overrides:
  electron-to-chromium: 1.5.400
onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - esbuild
  - '@nestjs/core'
  - '@scarf/scarf'
