ALTER TABLE "Product" ADD COLUMN "images" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Product" ADD COLUMN "deletedAt" TIMESTAMP(3);
CREATE TABLE "Media" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "mime" TEXT NOT NULL,
  "data" BYTEA NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "SiteContent" (
  "id" TEXT NOT NULL PRIMARY KEY,
  "data" JSONB NOT NULL
);
